name: Java CD with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi

            # Ensure Docker Compose is installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo wget "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64" -O /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose --version
            fi

            # Navigate to the directory containing docker-compose.yml
            cd /usr/local/bin/docker-compose-directory

            # Pull the latest Docker images and deploy containers
            echo "Deploying with Docker Compose..."
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
          timeout: 30s
          command_timeout: 10m
          debug: false
