name: Java CD with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Set permissions for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven Wrapper
        run: ./mvnw -B package

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with Docker Compose
        uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: ./docker-compose.yml
          command: build

      - name: Push Docker image with Docker Compose
        uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: ./docker-compose.yml
          command: push
